#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcdio
Version  : 2.0.0
Release  : 3
URL      : https://ftp.gnu.org/gnu/libcdio/libcdio-2.0.0.tar.bz2
Source0  : https://ftp.gnu.org/gnu/libcdio/libcdio-2.0.0.tar.bz2
Summary  : Portable CD-ROM I/O library
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: libcdio-bin
Requires: libcdio-lib
Requires: libcdio-doc
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)

%description
The libcdio package contains a library for CD-ROM and CD image
access. Applications wishing to be oblivious of the OS- and
device-dependent properties of a CD-ROM or of the specific details of
various CD-image formats may benefit from using this library.

%package bin
Summary: bin components for the libcdio package.
Group: Binaries

%description bin
bin components for the libcdio package.


%package dev
Summary: dev components for the libcdio package.
Group: Development
Requires: libcdio-lib
Requires: libcdio-bin
Provides: libcdio-devel

%description dev
dev components for the libcdio package.


%package doc
Summary: doc components for the libcdio package.
Group: Documentation

%description doc
doc components for the libcdio package.


%package lib
Summary: lib components for the libcdio package.
Group: Libraries

%description lib
lib components for the libcdio package.


%prep
%setup -q -n libcdio-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515694219
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1515694219
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cd-drive
/usr/bin/cd-info
/usr/bin/cd-read
/usr/bin/cdda-player
/usr/bin/iso-info
/usr/bin/iso-read
/usr/bin/mmc-tool

%files dev
%defattr(-,root,root,-)
/usr/include/cdio++/cdio.hpp
/usr/include/cdio++/cdtext.hpp
/usr/include/cdio++/device.hpp
/usr/include/cdio++/devices.hpp
/usr/include/cdio++/disc.hpp
/usr/include/cdio++/enum.hpp
/usr/include/cdio++/iso9660.hpp
/usr/include/cdio++/mmc.hpp
/usr/include/cdio++/read.hpp
/usr/include/cdio++/track.hpp
/usr/include/cdio/audio.h
/usr/include/cdio/bytesex.h
/usr/include/cdio/bytesex_asm.h
/usr/include/cdio/cd_types.h
/usr/include/cdio/cdio.h
/usr/include/cdio/cdio_config.h
/usr/include/cdio/cdtext.h
/usr/include/cdio/device.h
/usr/include/cdio/disc.h
/usr/include/cdio/ds.h
/usr/include/cdio/dvd.h
/usr/include/cdio/ecma_167.h
/usr/include/cdio/iso9660.h
/usr/include/cdio/logging.h
/usr/include/cdio/memory.h
/usr/include/cdio/mmc.h
/usr/include/cdio/mmc_cmds.h
/usr/include/cdio/mmc_hl_cmds.h
/usr/include/cdio/mmc_ll_cmds.h
/usr/include/cdio/mmc_util.h
/usr/include/cdio/posix.h
/usr/include/cdio/read.h
/usr/include/cdio/rock.h
/usr/include/cdio/sector.h
/usr/include/cdio/track.h
/usr/include/cdio/types.h
/usr/include/cdio/udf.h
/usr/include/cdio/udf_file.h
/usr/include/cdio/udf_time.h
/usr/include/cdio/utf8.h
/usr/include/cdio/util.h
/usr/include/cdio/version.h
/usr/include/cdio/xa.h
/usr/lib64/libcdio++.so
/usr/lib64/libcdio.so
/usr/lib64/libiso9660++.so
/usr/lib64/libiso9660.so
/usr/lib64/libudf.so
/usr/lib64/pkgconfig/libcdio++.pc
/usr/lib64/pkgconfig/libcdio.pc
/usr/lib64/pkgconfig/libiso9660++.pc
/usr/lib64/pkgconfig/libiso9660.pc
/usr/lib64/pkgconfig/libudf.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcdio++.so.1
/usr/lib64/libcdio++.so.1.0.0
/usr/lib64/libcdio.so.18
/usr/lib64/libcdio.so.18.0.0
/usr/lib64/libiso9660++.so.0
/usr/lib64/libiso9660++.so.0.0.0
/usr/lib64/libiso9660.so.11
/usr/lib64/libiso9660.so.11.0.0
/usr/lib64/libudf.so.0
/usr/lib64/libudf.so.0.0.0
